services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: payment-service
  stripe-cli:
    image: stripe/stripe-cli:latest
    command: ["listen", "--forward-to", "http://app:3000/api/webhooks/stripe"]
    depends_on:
      - app
